config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'}
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/edit'
  # resources :reservations
  # resources :user, only: [:index, :edit, :show, :update]
  # devise_for :users
  # devise_for :admins
  # devise_for :admins, controllers: {
  #   confirmaions: 'admin/sessions'
  # }
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  devise_for :admins , skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    # get 'admins/regular_holiday' => 'admins/salon_details#new_regular'
    # post 'admins/regular_holiday' => 'admins/salon_details#create_regular'
    # get 'admins/spcial_holiday' => 'admins/salon_details#new_spcial'
    # post 'admins/spcial_holiday' => 'admins/salon_details#create_spcial'
    # get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    # post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    # get 'admins/cancel' => 'admins/registrations#cancel', as: 'cancel_admin_registration'
    # get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    # patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # delete 'admins' => 'admins/registrations#delete', as: 'admin_registration'
  end
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'        
    patch 'users/password' => 'users/password#update', as: 'user_password' 
    put 'users/password' => 'users/password#update'  
    post 'users/password' => 'users/password#create'         
    get 'users/cancel' => 'users/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'users/registrations#update'
    put 'users' => 'users/registrations#update'
    delete 'users' => 'users/registrations#delete'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'user_details', to: 'users/registrations#new_detail'
    post 'user_details', to: 'users/registrations#create_detail'
    get "times", to: 'users/reservations#new_time'
  end
  
  namespace :users do
    resources :stylists
    resources :reservations do
      collection do 
        get :confirm
      end
      member do
        get :edit_menu
        get :edit_confirm
        patch :update_menu
      end
    end
    resources :users
   
  end
  namespace :admins do
    resources :users do
      resources :user_options
    end 
    resources :reservations
    resources :stylists 
    resources :menus
    resources :salons do
      resources :salon_details do
        collection do
          get :new_regular
          post :create_regular
          get :new_spcial
          post :create_spcial
        end
      end
      resources :shifts
    end
      resources :spcial_holidays
  end
  root to: "users/users#index"
end

app/models/salon_detail.rb
class SalonDetail < ApplicationRecord
  belongs_to :salon
  has_many :salon_spcial_holidays, dependent: :destroy
  has_many :spcial_holidays, through: :salon_spcial_holidays
  has_many :salon_shifts, dependent: :destroy
  has_many :shift_salons, through: :salon_shifts
  has_many :salon_regular_holidays, dependent: :destroy
  has_many :regular_holidays, through: :salon_regular_holidays
end

app/controllers/admins/salon_details_controller.rb
class Admins::SalonDetailsController < ApplicationController
  before_action :set_salon
  def index
    @date = Date.today 
  end
  
  def new_regular
    @salon_detail = SalonDetail.new
  end

  def create_regular
    @salon_detail = SalonDetail.new(regular_params)
    if @salon_detail.save
      redirect_to admins_salon_salon_details_path(current_admin.salon.id)
    else
      render :new_regular
    end
  end
  

  def new
    @salon_detail = SalonDetail.new
  end

  private

  def regular_params
    params.require(:salon_detail).permit({regular_holiday_ids: []}).merge(salon_id: current_admin.salon.id)
  end

  def set_salon
    @salon = Salon.find(params[:salon_id])
  end
end

app/helpers/salon_details_helper.rb
module SalonDetailsHelper
end

app/views/admins/salon_details/index.html.erb
<%= render "shared/header_salon" %>
<div class="contents">
  <div class="section">
    <div class="holiday_all">
      <div class="regular_holiday_area">
        <%= link_to  new_regular_admins_salon_salon_details_path(current_admin.salon.id) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                定休日設定
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                曜日で毎週休みが決まってる<br>
                定休日の設定はこちらからしてください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="spcial_holiday_area">
        <%= link_to new_admins_spcial_holiday_path(date:@date.next_month) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.next_month.strftime("%Y年%m月") %>休日設定
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で入力してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="spcial_holiday_area">
        <%= link_to  new_admins_salon_shift_path(current_admin.salon.id) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.next_month.strftime("%Y年%m月") %>休日設定(スタッフ)
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                前月までに設定お願い致します。<br>
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
    <div class="customer_title">
        <p class="block_area"></p>
        <h1 style="background-color:#9b9b9b;color:white;"class="title1 stylist_space">店休日(先々予定)</h1>
     </div>
     <div class="holiday_all">
       <div class="spcial_holiday_area">
        <%= link_to new_spcial_admins_salon_salon_details_path(current_admin.salon.id, date:@date.months_since(2)) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.months_since(2).strftime("%Y年%m月") %>休日設定
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="spcial_holiday_area">
        <%= link_to new_spcial_admins_salon_salon_details_path(current_admin.salon.id, date:@date.months_since(3)) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.months_since(3).strftime("%Y年%m月") %>休日設定
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
       <div class="spcial_holiday_area">
        <%= link_to new_spcial_admins_salon_salon_details_path(current_admin.salon.id, date: @date.months_since(4)) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.months_since(4).strftime("%Y年%m月") %>休日設定
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
    <div class="customer_title">
        <p class="block_area"></p>
        <h1 style="background-color:#9b9b9b;color:white;"class="title1 stylist_space">スタッフ休日(先々予定)</h1>
    </div>
    <div class="holiday_all">
      <div class="spcial_holiday_area">
          <%= link_to  new_admins_salon_shift_path(current_admin.salon.id) do %>
            <table class="regular_holiday_table">
              <tr>
                <th class="regular_holiday_th">
                  <%= @date.months_since(2).strftime("%Y年%m月") %>休日設定(スタッフ)
                </th>
              </tr>
              <tr>
                <td class="regular_holiday_td">
                  特定の日付で選択してください
                </td>
              </tr>
            </table>
          <% end %>
      </div>
      <div class="spcial_holiday_area">
        <%= link_to  new_admins_salon_shift_path(current_admin.salon.id) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.months_since(3).strftime("%Y年%m月") %>休日設定(スタッフ)
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="spcial_holiday_area">
        <%= link_to  new_admins_salon_shift_path(current_admin.salon.id) do %>
          <table class="regular_holiday_table">
            <tr>
              <th class="regular_holiday_th">
                <%= @date.months_since(2).strftime("%Y年%m月") %>休日設定(スタッフ)
              </th>
            </tr>
            <tr>
              <td class="regular_holiday_td">
                特定の日付で選択してください
              </td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
    <div class="holiday_display">
      <div class="customer_title">
        <p class="block_area"></p>
        <h1 style="background-color:#9b9b9b;color:white;"class="title1 stylist_space">登録している休日一覧</h1>
      </div>
      <table class="holiday_regular_table">
        <tr>
          
        </tr>
      </table>
    </div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/admins/salon_details/new_regular.html.erb
<%= render "shared/header_salon" %>
<div class="contents">
  <div class="section">
    <div class="new_regular_area">
      <div class="customer_title">
          <p class="block_area"></p>
          <h1 style="background-color:#9b9b9b;color:white;"class="title1 stylist_space">定休日登録</h1>
      </div>
      <%= form_with model:[@salon, @salon_detail], url: create_regular_admins_salon_salon_details_path(@salon.id), local: true do |f|%>
        <table class="new_regular_table">
          <colgroup width="30%"></colgroup>
          <colgroup width="70%"></colgroup>
          <tr>
            <th class="new_regular_th">
              定休日(曜日を選択してください)<br>複数選択可
            </th>
            <td class="new_regular_td">
              <%= f.collection_check_boxes(:regular_holiday_ids, RegularHoliday.all, :id, :name,{include_hidden: false},{class:"regular_check_box"}  ) %>
            </td>
          </tr>
        </table>
        <div class="submit_save">
           <p class="registration_area">
             <%= f.submit "登録する", class:"registration" %>
           </p>
        </div> 
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/admins/salon_details/new_spcial.html.erb
<%= render "shared/header_salon" %>
<div class="contents">
  <div class="section">
    <div class="new_spcial_area">
      <div class="customer_title">
          <p class="block_area"></p>
          <h1 style="background-color:#9b9b9b;color:white;"class="title1 stylist_space">12月休日登録</h1>
      </div>
      <%= form_with model: [@salon, @salon_detail], url: create_spcial_admins_salon_salon_details_path(@salon.id), local: true do |f| %>
        <table class="new_spcial_table">
          <colgroup width="30%"></colgroup>
          <colgroup width="70%"></colgroup>
          
          <tr>
        </table>
      <% end %>
    </div>
  </div>
</div>