config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'}
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/edit'
  # resources :reservations
  # resources :user, only: [:index, :edit, :show, :update]
  # devise_for :users
  # devise_for :admins
  # devise_for :admins, controllers: {
  #   confirmaions: 'admin/sessions'
  # }
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  devise_for :admins , skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    # get 'admins/regular_holiday' => 'admins/salon_details#new_regular'
    # post 'admins/regular_holiday' => 'admins/salon_details#create_regular'
    # get 'admins/spcial_holiday' => 'admins/salon_details#new_spcial'
    # post 'admins/spcial_holiday' => 'admins/salon_details#create_spcial'
    # get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    # post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    # get 'admins/cancel' => 'admins/registrations#cancel', as: 'cancel_admin_registration'
    # get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    # patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # delete 'admins' => 'admins/registrations#delete', as: 'admin_registration'
  end
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'        
    patch 'users/password' => 'users/password#update', as: 'user_password' 
    put 'users/password' => 'users/password#update'  
    post 'users/password' => 'users/password#create'         
    get 'users/cancel' => 'users/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'users/registrations#update'
    put 'users' => 'users/registrations#update'
    delete 'users' => 'users/registrations#delete'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'user_details', to: 'users/registrations#new_detail'
    post 'user_details', to: 'users/registrations#create_detail'
    get "times", to: 'users/reservations#new_time'
  end
  
  namespace :users do
    resources :stylists
    resources :reservations do
      collection do 
        get :confirm
      end
      member do
        get :edit_menu
        get :edit_confirm
        patch :update_menu
      end
    end
    resources :users
   
  end
  namespace :admins do
    resources :users do
      resources :user_options
    end 
    resources :reservations
    resources :stylists 
    resources :menus
    resources :salons do
      resources :salon_details do
        collection do
          get :new_regular
          post :create_regular
          get :new_spcial
          post :create_spcial
        end
      end
      resources :shifts
    end
      resources :spcial_holidays
  end
  root to: "users/users#index"
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="path">
   <div class="path-section">
    <p>sample様 / number / 即時予約 / サロン代表者名 / 管理ID / </p>
   </div>
  </div>
  <div class="footer" id="footer" style="min-height: 90px;">
   <div class="area-section">
    <div class="link_area">
     <ul class="link_cf">
       <li>
        <%= link_to "お問い合わせ", "#", class:"link-icon", id:"inquiry" %>
       </li>
       <li>
        <%= link_to "利用規約", "#", class:"link-icon", id:"terms" %>
       </li>
       <li>
        <%= link_to "プライバシーポリシー", "#", class:"link-icon", id:"privacy_policy" %>
       </li>
       <li>
        <%= link_to "ヘルプ", "#", class:"link-icon", id:"online_manual" %>
       </li>
     </ul>
    </div>
   </div>
    <div class="address">
     <p class="logo1" id="logo1">
      <%= link_to image_tag("salone-logo.png", class:"salone-icon1"), "/" %>
     </p>     
     <p class="company">
      <%= link_to "会社名", "#", class:"company_name" %>
     </p>
    </div>
  </div>
</footer>

app/views/shared/_footer_reservation_index.html.erb
<footer class="page-footer1">
  <div class="path">
   <div class="path-section">
    <p>sample様 / number / 即時予約 / サロン代表者名 / 管理ID / </p>
   </div>
  </div>
  <div class="footer" id="footer" style="min-height: 90px;">
   <div class="area-section">
    <div class="link_area">
     <ul class="link_cf">
       <li>
        <%= link_to "お問い合わせ", "#", class:"link-icon", id:"inquiry" %>
       </li>
       <li>
        <%= link_to "利用規約", "#", class:"link-icon", id:"terms" %>
       </li>
       <li>
        <%= link_to "プライバシーポリシー", "#", class:"link-icon", id:"privacy_policy" %>
       </li>
       <li>
        <%= link_to "ヘルプ", "#", class:"link-icon", id:"online_manual" %>
       </li>
     </ul>
    </div>
   </div>
    <div class="address">
     <p class="logo1" id="logo1">
      <%= link_to image_tag("salone-logo.png", class:"salone-icon1"), "/" %>
     </p>     
     <p class="company">
      <%= link_to "会社名", "#", class:"company_name" %>
     </p>
    </div>
  </div>
  <div class="calendar">
    <div class="inner" id="calendar_area">
      <div class="section_wf">
        <div class="calendar_block01">
          <p class="block one" id="openCalendar">
            <%= link_to admins_reservations_path do %>
               <%= image_tag("calendar.png", class:"btn_calendar_01") %>
            <% end %>
          </p>
          <p class="block two">
            <%= link_to image_tag("today.png", class:"btn_calendar_02"), "#" %>
          </p>
          <p class="block three">
            <%= link_to image_tag("previousday.png", class:"btn_calendar_03"), "#" %>
          </p>
          <dl class="date">
            <dd class="four">
              <ul class="day">
                <li class="sat">
                  <%= link_to "2", "#" %>
                </li>
                <li class="sun">
                  <%= link_to "2", "#" %>
                </li>
                <li class="today">
                  <%= link_to "2", "#" %>
                </li>
                <li class>
                  <%= link_to "2", "#" %>
                </li>
                <li class>
                  <%= link_to "2", "#" %>
                </li>
                <li class>
                  <%= link_to "2", "#" %>
                </li>
                <li class>
                  <%= link_to "2", "#" %>
                </li>
              </ul>
            </dd>
          </dl>
            <p class="block five">
            <%= link_to image_tag("nextday.png", class:"btn_calendar_04"), "#" %>
            </p>
        </div>
     </div>
  </div> 
</footer>

app/views/shared/_footer_root.html.erb
<footer class="calendar1">
   <div class="book_area">
        <%= link_to "予約する", users_reservations_path, class:"book_btn1"%>
   </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  
    <div class="header" id="header-name"> 
      <div class="header-section">
        <p class="logo" id="logo">
        <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
        </p>     
        <div class="btn_area" id="bot-all">
          <ul class="shop_name_wrap">
            <li class="shop_area">ヘアサロン</li>
            <% if current_admin.salon.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
          </ul>
          <ul class="btn-all">
            <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
            <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
            <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"stylist_management"%></li>
            <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
            <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="btn-bottom" id="btn-bottom">
      <div class="section-bottom">
        <div class="btn-column">
          <ul class="column-all">
            <% if current_page?(admins_reservations_path) %>
              <li><%= link_to "スケジュール", "#", class:"schedule"%></li>
              <li><%= link_to "予約一覧", "#", class:"reservation-list"%></li>
            <% elsif current_page?(controller: "admins/users", action: "index") || current_page?(controller: "admins/users", action: "new") || current_page?(controller: "admins/users", action: "edit") || current_page?(controller: "admins/users", action: "show") %> 
              <li><%= link_to "お客様一覧", admins_users_path, class:"customer-list" %></li>
              <li><%= link_to "登録", new_admins_user_path, class:"customer-list" %></li>
              <li><%= link_to "変更", "#", class:"customer-list" %></li>
              <li><%= link_to "削除", "#", class:"customer-list" %></li>
            <% elsif current_page?(controller: "admins/stylists", action: "index") || current_page?(controller: "admins/stylists", action: "new") || current_page?(controller: "admins/stylists", action: "edit") || current_page?(controller: "admins/stylists", action: "show") %>
              <li><%= link_to "スタイリスト一覧", admins_stylists_path, class:"stylist_list1" %></li>
              <li><%= link_to "スタイリスト登録", new_admins_stylist_path, class:"stylist_list1"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
   

</header>

app/views/shared/_header_menu.html.erb
<header class='top-page-header'>
  <div class="header" id="header-name"> 
    <div class="header-section">
      <p class="logo" id="logo">
       <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
      </p>     
      <div class="btn_area" id="bot-all">
        <ul class="shop_name_wrap">
          <li class="shop_area">ヘアサロン</li>
           <% if current_admin.salon.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
        </ul>
        <ul class="btn-all">
          <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
          <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
          <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom" id="btn-bottom">
    <div class="section-bottom">
      <div class="btn-column">
        <ul class="column-all">
          <% if current_page?(controller: "admins/menus", action: "index") || current_page?(controller: "admins/menus", action: "new") || current_page?(controller: "admins/menus", action: "edit") || current_page?(controller: "admins/menus", action: "show") %>
            <li><%= link_to "メニュ一覧", admins_menus_path, class:"stylist_list1" %></li>
            <li><%= link_to "メニュー登録", new_admins_menu_path, class:"stylist_list1"%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
   

</header>

app/views/shared/_header_mypage.html.erb
<header class="header_view">
  <div class="salon_view_top">
    <div class="salon_view_area">
      <div class="salon_icon_view">
        <%= link_to image_tag("salone-logo.png", class:"salon-icon-view"), "/" %>
      </div>
    </div>
    <% unless user_signed_in? %>
      <div class="salon_view_right">
        <h1 class="salon_name_view">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))
          <p class="salon_name_cana">サンプルフリカナ(ラ・ヴィ・アン・ルフレット)</p>
          <p class="salon_view_address">サンプル住所(〒206-0824東京都稲城市若葉台２−５−６)</p>
        </h1>
      </div>
    <% else %>
      <div class="salon_view_right">
          <h1 class="salon_name_view"> <%= current_user.salon.salon_name %>
            <p class="salon_name_cana"><%= current_user.salon.salon_name_cana %></p>
            <p class="salon_view_address">〒<%= current_user.salon.post_code%><%= current_user.salon.prefecture.name%><%= current_user.salon.address_all%></p>
          </h1>
      </div>
    <% end %>
    <div class="salon_log_all">
      <div class="book_area">
        <%= link_to "予約する", users_reservations_path, class:"book_btn"%>
      </div>
        <ul class="salon_log_btn_area">
          <% if user_signed_in? %>
            <li class="salon_new_btn_li">
              <%= link_to "トップページ", root_path, class:"salon_new_btn"%>
            </li>
            <li class="salon_log_btn_li">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"salon_log_btn" %>
            </li>
          <% elsif admin_signed_in? %>
            <% if Salon.count == 0 %>
              <li class="salon_new_btn_li">
                <%= link_to "管理者画面", new_admins_salon_path, class:"salon_new_btn1"%>
              </li>
            <% else %>
              <li class="salon_new_btn_li">
                <%= link_to "管理者画面", admins_salons_path, class:"salon_new_btn1"%>
              </li>
            <% end %>
            <li class="salon_log_btn_li">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"salon_log_btn" %>
            </li>
          <% else %>
            <li class="salon_new_btn_li">
              <%= link_to "新規登録", new_user_registration_path, class:"salon_new_btn"%>
            </li>
            <li class="salon_log_btn_li">
              <%= link_to "ログイン", new_user_session_path, class:"salon_log_btn" %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</header>

app/views/shared/_header_salon.html.erb
<header class='top-page-header'>
  <div class="header" id="header-name"> 
    <div class="header-section">
      <p class="logo" id="logo">
       <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
      </p>     
      <div class="btn_area" id="bot-all">
        <ul class="shop_name_wrap">
          <li class="shop_area">ヘアサロン</li>
          <% if current_admin.salon.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
        </ul>
        <ul class="btn-all">
          <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
          <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
          <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom" id="btn-bottom">
    <div class="section-bottom">
      <div class="btn-column">
        <ul class="column-all">
            <li><%= link_to "サロン情報", admins_salons_path, class:"stylist_list1" %></li>
            <% if current_page?(controller: "admins/salons", action: "new") %>
            <% else%>
              <li><%= link_to "詳細情報", admins_salon_salon_details_path(current_admin.salon.id), class:"stylist_list1" %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_stylist.html.erb
<header class='top-page-header'>
  <div class="header" id="header-name"> 
    <div class="header-section">
      <p class="logo" id="logo">
       <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
      </p>     
      <div class="btn_area" id="bot-all">
        <ul class="shop_name_wrap">
          <li class="shop_area">ヘアサロン</li>
          <% if current_admin.salon.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
        </ul>
        <ul class="btn-all">
          <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
          <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
          <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom" id="btn-bottom">
    <div class="section-bottom">
      <div class="btn-column">
        <ul class="column-all">
          <% if current_page?(controller: "admins/stylists", action: "index") || current_page?(controller: "admins/stylists", action: "new") || current_page?(controller: "admins/stylists", action: "edit") || current_page?(controller: "admins/stylists", action: "show") %>
            <li><%= link_to "スタイリスト一覧", admins_stylists_path, class:"stylist_list1" %></li>
            <li><%= link_to "スタイリスト登録", new_admins_stylist_path, class:"stylist_list1"%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
   

</header>

app/views/shared/_header_top.html.erb
<header class="header_view">
  <div class="salon_view_top">
    <div class="salon_view_area">
      <div class="salon_icon_view">
        <%= link_to image_tag("salone-logo.png", class:"salon-icon-view"), "/" %>
      </div>
    </div>
    <% unless user_signed_in? %>
      <div class="salon_view_right">
        <h1 class="salon_name_view">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))
          <p class="salon_name_cana">サンプルフリカナ(ラ・ヴィ・アン・ルフレット)</p>
          <p class="salon_view_address">サンプル住所(〒206-0824東京都稲城市若葉台２−５−６)</p>
        </h1>
      </div>
    <% else %>
      <div class="salon_view_right">
          <h1 class="salon_name_view"> <%= current_user.salon.salon_name %>
            <p class="salon_name_cana"><%= current_user.salon.salon_name_cana %></p>
            <p class="salon_view_address">〒<%= current_user.salon.post_code%><%= current_user.salon.prefecture.name%><%= current_user.salon.address_all%></p>
          </h1>
      </div>
    <% end %>
    <div class="salon_log_all">
      <div class="book_area">
          <%= link_to "予約する", users_reservations_path, class:"book_btn"%>
      </div>
        <ul class="salon_log_btn_area">
          <% if user_signed_in? %>
            <li class="salon_new_btn_li">
              <%= link_to "マイページ", users_user_path(current_user.id), class:"salon_new_btn"%>
            </li>
            <li class="salon_log_btn_li">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"salon_log_btn" %>
            </li>
          <% elsif admin_signed_in? %>
            <% if current_admin.salon.blank? %>
              <li class="salon_new_btn_li">
                <%= link_to "サロン登録", new_admins_salon_path, class:"salon_new_btn1"%>
              </li>
            <% else %>
              <li class="salon_new_btn_li">
                <%= link_to "管理者画面", admins_reservations_path, class:"salon_new_btn1"%>
              </li>
            <% end %>
            <li class="salon_log_btn_li">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"salon_log_btn" %>
            </li>
          <% else %>
            <li class="salon_new_btn_li">
              <%= link_to "新規登録", new_user_registration_path, class:"salon_new_btn"%>
            </li>
            <li class="salon_log_btn_li">
              <%= link_to "ログイン", new_user_session_path, class:"salon_log_btn" %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
  <div class="salon_view_bottom">
    <% if user_signed_in? %>
      <ul class="salon_view_bottom_ul">
        <li class="salon_information_area">
          <%= link_to "サロン情報", "#", class:"salon_information_btn" %>
        </li>
        <li class="salon_information_area">
          <%= link_to "メニュー", users_reservations_path, class:"salon_information_btn" %>
        </li>
        <li class="salon_information_area">
          <%= link_to "スタイリスト", users_stylists_path, class:"salon_information_btn" %>
        </li>
        <li class="salon_information_area">
          <%= link_to "スタイル", "#", class:"salon_information_btn" %>
        </li>
        <li class="salon_information_area">
          <%= link_to "地図", "#", class:"salon_information_btn" %>
        </li>
        <li class="salon_information_area">
          <%= link_to "ブログ", "#", class:"salon_information_btn" %>
        </li>
      </ul>
    <% end %>
  </div>
</header>

app/views/shared/_header_user.html.erb
<header class='top-page-header'>
  <div class="header" id="header-name"> 
    <div class="header-section">
      <p class="logo" id="logo">
       <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
      </p>     
      <div class="btn_area" id="bot-all">
        <ul class="shop_name_wrap">
          <li class="shop_area">ヘアサロン</li>
         <% if current_admin.salon.salon_name.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
        </ul>
        <ul class="btn-all">
          <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
          <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
          <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom" id="btn-bottom">
    <div class="section-bottom">
      <div class="btn-column">
        <ul class="column-all">
          <% if current_page?(controller: "admins/users", action: "index") || current_page?(controller: "admins/users", action: "new") || current_page?(controller: "admins/users", action: "edit") || current_page?(controller: "admins/users", action: "show") %> 
            <li><%= link_to "お客様一覧", admins_users_path, class:"customer-list" %></li>
            <li><%= link_to "登録", new_admins_user_path, class:"customer-list" %></li>
            <li><%= link_to "変更", "#", class:"customer-list" %></li>
            <li><%= link_to "削除", "#", class:"customer-list" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
   

</header>

app/views/shared/_header_user_option.html.erb
<header class='top-page-header'>
  <div class="header" id="header-name"> 
    <div class="header-section">
      <p class="logo" id="logo">
       <%= link_to image_tag("salone-logo.png", class:"salone-icon"), "/" %>
      </p>     
      <div class="btn_area" id="bot-all">
        <ul class="shop_name_wrap">
          <li class="shop_area">ヘアサロン</li>
          <% if current_admin.salon.blank? %>
            <li class="shop_name">サンプル(La Vie en Reflet(ラ・ヴィ・アン・ルフレット))</li>
          <% else %>
            <li class="shop_name"><%= current_admin.salon.salon_name %>(<%= current_admin.salon.salon_name_cana %>)</li>
          <% end %>
        </ul>
        <ul class="btn-all">
          <li><%= link_to "予約管理", admins_reservations_path, class:"management"%></li>
          <li><%= link_to "お客様管理", admins_users_path, class:"user-management"%></li>
          <li><%= link_to "スタイリスト管理", admins_stylists_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗管理", admins_salons_path ,class:"salon_management"%></li>
          <li><%= link_to "店舗メニュー", admins_menus_path, class: "salon_management" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="btn-bottom" id="btn-bottom">
    <div class="section-bottom">
      <div class="btn-column">
        <ul class="column-all">
            <li><%= link_to "時間設定一覧", admins_user_user_options_path(user_id: @user), class:"customer-list" %></li>
            <li><%= link_to "時間登録", new_admins_user_user_option_path(user_id: @user), class:"customer-list" %></li>
            <li><%= link_to "変更", "#", class:"customer-list" %></li>
            <li><%= link_to "削除", "#", class:"customer-list" %></li>
        </ul>
      </div>
    </div>
  </div>
   

</header>