config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'}
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/edit'
  # resources :reservations
  # resources :user, only: [:index, :edit, :show, :update]
  # devise_for :users
  # devise_for :admins
  # devise_for :admins, controllers: {
  #   confirmaions: 'admin/sessions'
  # }
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }
  devise_for :admins , skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    # get 'admins/regular_holiday' => 'admins/salon_details#new_regular'
    # post 'admins/regular_holiday' => 'admins/salon_details#create_regular'
    # get 'admins/spcial_holiday' => 'admins/salon_details#new_spcial'
    # post 'admins/spcial_holiday' => 'admins/salon_details#create_spcial'
    # get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    # post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    # get 'admins/cancel' => 'admins/registrations#cancel', as: 'cancel_admin_registration'
    # get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    # patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    # delete 'admins' => 'admins/registrations#delete', as: 'admin_registration'
  end
  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    get 'users/password/edit' => 'users/passwords#edit', as: 'edit_user_password'        
    patch 'users/password' => 'users/password#update', as: 'user_password' 
    put 'users/password' => 'users/password#update'  
    post 'users/password' => 'users/password#create'         
    get 'users/cancel' => 'users/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'users/registrations#update'
    put 'users' => 'users/registrations#update'
    delete 'users' => 'users/registrations#delete'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'user_details', to: 'users/registrations#new_detail'
    post 'user_details', to: 'users/registrations#create_detail'
    get "times", to: 'users/reservations#new_time'
  end
  
  namespace :users do
    resources :stylists
    resources :reservations do
      collection do 
        get :confirm
      end
      member do
        get :edit_menu
        get :edit_confirm
        patch :update_menu
      end
    end
    resources :users
   
  end
  namespace :admins do
    resources :users do
      resources :user_options
    end 
    resources :reservations
    resources :stylists 
    resources :menus
    resources :salons do
      resources :salon_details do
        collection do
          get :new_regular
          post :create_regular
          get :new_spcial
          post :create_spcial
        end
      end
      resources :shifts
    end
      resources :spcial_holidays
  end
  root to: "users/users#index"
end

app/models/user_option.rb
class UserOption < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :menu_time
  belongs_to :user,  optional: true
  belongs_to :menu,  optional: true
  
end

app/controllers/admins/user_options_controller.rb
class Admins::UserOptionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user
  before_action :set_user_option, only: [:edit, :update, :destroy]
  def index 
    @user_options = UserOption.all
    # binding.pry
  end
  
  def new
    # binding.pry
    @user_option = UserOption.new
  end

  def create
    @user_option = UserOption.new(user_option_params)
    if @user_option.save
      redirect_to admins_user_user_options_path(user_id: @user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user_option.update(user_option_params)
      redirect_to admins_reservations_path
    else
      render :edit
    end
  end

  def destroy
    if @user_option.destroy
      redirect_to admins_reservations_path
    else
      render :index
    end
  end

  private

  def user_option_params
    params.require(:user_option).permit(:menu_time_id, :menu_id).merge(user_id: @user.id)
  end

  def set_user
    @user = User.find(params[:user_id])
    @salon = @user.salon
    # @user = User.find_by(id: params[:format])
  end

  def set_user_option
    @user_option = UserOption.find(params[:id])
  end


end

app/helpers/user_options_helper.rb
module UserOptionsHelper
end

app/views/admins/user_options/edit.html.erb
<%= render "shared/header_user_option" %>
<div class="contents">
  <div class="section">
    <%= form_with model: [@user, @user_option], url: admins_user_user_option_path(@user.id,@user_option.id), method: :patch, id: 'new_menu', local: true do |f| %>
      <table class="new_menu" style="margin-top:10px;">
        <tr>
            <th>メニュー情報
              <p class="block_area"></p>
            </th>
        </tr>
      </table>
      <table class="new_time_option1" style="margin-top:15px;margin-bottom:30px;">
        <colgroup width="20%"></colgroup>
        <colgroup width="15%"></colgroup>
        <colgroup width="10%"></colgroup>
        <colgroup width="10%"></colgroup>
        <colgroup width="35%"></colgroup>
        <colgroup width="10%"></colgroup>
        <tr>
          <th colspan="1" class="stylist_input_name">施術カテゴリー<span class="circle">🔴</span></th>
          <td colspan="5" style="border:1px solid black;" class="stylist_td">
           <%= f.collection_select(:menu_id, Menu.all, :id, :menu_name,{include_blank: "--"},{class:"option_category_check"}) %>
          </td>
        </tr>
        <tr class="stylist_tr">
          <th colspan="1" class="stylist_input_name">メニュー時間<span class="circle">🔴</span></th>
          <td class="stylist_td" colspan="3" style="border:1px solid black;">
            <%= f.collection_select(:menu_time_id, MenuTime.all, :id, :name ,{class:"menu_select", id:"menu_time"}) %>
          </td>
        </tr>
      </table>
      <table style="width:100%;height:20px;margin-top:30px;">
        <tr>
          <td class="register_td">
            <ul class="stylist_register_btn">
              <li>
                <%= f.submit "登録", class:"register_btn"%>
              </li>
              <li class="stylist_cancel_btn">
                <%= link_to "キャンセル", url: admins_users_path, class:"cancel_btn" %>
              </li>
            </ul>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>
<%= render "shared/footer"%>

app/views/admins/user_options/index.html.erb
<%= render "shared/header_user_option" %>
<div class="contents">
  <div class="section">
    <div class="user_option_area">
      <table class="time_index_table2" style="float:left;margin-bottom:30px;">
        <tr>
          <th class="user_option_title">お客様情報
            <p class="block_area"></p>
          </th>
        </tr>
      </table>
      <table class="user_option_title1" align="left" style="margin-bottom:30px;">
        <colgroup width="15%"></colgroup>
        <colgroup width="35%"></colgroup>
        <tr>
          <th class="show_name">氏名(漢字)</th>
          <td class="show_bd">
            <span class="show_field"><%=  @user.first_name.to_s +   @user.last_name.to_s  %></span>
          </td>
        </tr>
      </table>
      <table class="user_option_title1">
        <tr>
          <th class="show_name">氏名(カナ)</th>
          <td class="show_bd">
            <span class="show_field"><%=  @user.first_name_cana.to_s +   @user.last_name_cana.to_s %></span>
          </td>
        </tr>
      </table>
      <table class="time_index_table2" style="margin-bottom:30px;">
        <tr>
          <th class="user_option_title">メニュー時間設定
            <p class="block_area"></p>
          </th>
        </tr>
      </table>
      <table class="time_index_table" style="margin-bottom:30px;">
        <colgroup width="30%"></colgroup>
        <colgroup width="50%"></colgroup>
        <colgroup width="10%"></colgroup>
        <colgroup width="10%"></colgroup>
        <% @user_options.each do |option|%>
          <% unless option.menu_id == 0 %>
           <% if @user.id == option.user_id %>
            <tr>
              <th class="show_name index_user_option_th">時間設定メニュー</th>
              <td colspan="3" class="show_bd">
                <span class="show_field"><%= option.menu.menu_name  %>
              </td>
            </tr>
            <tr>
              <th class="show_name">設定マイナス時間</th>
              <td class="show_bd index_user_option_td">
                <span class="show_field">-<%= option.menu_time.name  %></span>
              </td>
              <td class="show_bd">
                <%= link_to "編集", edit_admins_user_user_option_path(@user,option.id), class:"stylist_show" %>
              </td>
              <td class="show_bd">
                <%= link_to "削除", admins_user_user_option_path(@user,option.id), method: :delete, id:"style_delete", class: "stylist_delete", data: { confirm: "本当に削除しますか？"} %>
              </td>
            </tr>
           <% end %>
          <% end%>
        <% end %>
      </table>
      <div class="stylist_display">
        <p class="option_time">
          <%= link_to "個人時間登録", new_admins_user_user_option_path(@user.id), class:"time_add" %>
        </p>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/admins/user_options/new.html.erb
<%= render "shared/header_user_option" %>
<div class="contents">
  <div class="section">
    <%= form_with model: [@user, @user_option], url: admins_user_user_options_path(@user.id), id: 'new_menu', local: true do |f| %>
      <table class="new_menu" style="margin-top:10px;">
        <tr>
            <th>メニュー情報
              <p class="block_area"></p>
            </th>
        </tr>
      </table>
      <table class="new_time_option1" style="margin-top:15px;margin-bottom:30px;">
        <colgroup width="20%"></colgroup>
        <colgroup width="15%"></colgroup>
        <colgroup width="10%"></colgroup>
        <colgroup width="10%"></colgroup>
        <colgroup width="35%"></colgroup>
        <colgroup width="10%"></colgroup>
        <tr>
          <th colspan="1" class="stylist_input_name">施術カテゴリー<span class="circle">🔴</span></th>
          <td colspan="5" style="border:1px solid black;" class="stylist_td">
           <%= f.collection_select(:menu_id, Menu.all, :id, :menu_name,{include_blank: "--"},{class:"option_category_check"}) %>
          </td>
        </tr>
        <tr class="stylist_tr">
          <th colspan="1" class="stylist_input_name">メニュー時間<span class="circle">🔴</span></th>
          <td class="stylist_td" colspan="3" style="border:1px solid black;">
            <%= f.collection_select(:menu_time_id, MenuTime.all, :id, :name ,{class:"menu_select", id:"menu_time"}) %>
          </td>
        </tr>
      </table>
      <table style="width:100%;height:20px;margin-top:30px;">
        <tr>
          <td class="register_td">
            <ul class="stylist_register_btn">
              <li>
                <%= f.submit "登録", class:"register_btn"%>
              </li>
              <li class="stylist_cancel_btn">
                <%= link_to "キャンセル", url: admins_users_path, class:"cancel_btn" %>
              </li>
            </ul>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>
<%= render "shared/footer"%>